### ISSUE TITLE
openwrt的已经不能用了

### ISSUE THREAD

**Issue by guanzhongpy** [ehaut/ehaut#6]
openwrt端一直显示的是bas respond timeout， 大神可否指点一二

**Comment by CHN-STUDENT** [comment]
您要不要试试改改ac_id的值试一下？
>         "ac_id": 1,
一般有1 或 2两种，不行您可以改另外一个试试

**Comment by guanzhongpy** [comment]
> 您要不要试试改改ac_id的值试一下？
> 
> > ```
> >     "ac_id": 1,
> > ```
> 
> 一般有1 或 2两种，不行您可以改另外一个试试

ac_id 改为2后显示的user no found
是不是他的这种po_dict["username"] = "{SRUN3}\r\n" + usr_encrypt(account) 过时了？

**Comment by CHN-STUDENT** [comment]
@guanzhongpy 您好，我同学同样使用openwrt版本并未发现此问题（https://github.com/ehaut/autologin-srun3k)，    请您参考此教程配置重试或提供更多信息以便我们排查。
感谢

**Comment by guanzhongpy** [comment]
> @guanzhongpy您好，我同学同样使用openwrt版本重新发现此问题（[https://github.com/ehaut/autologin-srun3k），](https://github.com/ehaut/autologin-srun3k)%EF%BC%8C) 请您参考此教程配置重试或提供更多信息盔甲我们排查。
> 感谢

很高兴的告知您我已经解决。
具体方法如下：
在openwrt中opkg libustream-mbedtls来实现wget https
再将autologin.py 91和112行ac_id更改为2即可
我发现必须用wget的方法获得的文件才能正确运行，SCP传输的文件就无法正确运行，喵喵喵？
最后，感谢大佬们的付出和努力
此上

**Comment by CHN-STUDENT** [comment]
@guanzhongpy 好的那我关闭此issue了，如果您有其他需要，欢迎跟帖或者打开issue。
